version: '3.7'
services:
  app:
    container_name: api
    build: ./
    ports:
      - "9000:8080"
    environment:
      - PRING_DATASOURCE_PASSWORD=postgres
      - PRING_DATASOURCE_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    links:
      - postgres
  postgres:
    build: src/main/resources/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
