version: '3.7'
services:
  app:
    container_name: api
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    build: ../src/main/resources/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
